# Generated by Django 4.2.4 on 2023-08-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_profile_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='Profile/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FileField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
